### ISSUE TITLE
Game over errors spaceinvader

### ISSUE THREAD

**Issue by Herschel-The-Cauchois** [Herschel-The-Cauchois/Efrarcade-TheHowls#16]
Error when clicking to close the spaceinvader window
![image](https://github.com/Herschel-The-Cauchois/Efrarcade-TheHowls/assets/133710162/22b79604-f4e5-4a2c-bffe-9451c0968855)

Out of range when writing new user score at game over
![image](https://github.com/Herschel-The-Cauchois/Efrarcade-TheHowls/assets/133710162/e5acfb34-637f-4128-a7f6-1431655225fb)

**Comment by Pverte** [comment]
First error : comes when you restart the game and quit it, and when you start the game from the menu.
It's not very important as it's just pygame that don't like that we quit the game before we quit the surface. To check if there is some perfomances issues with it but it's not important for now.
I tried to change some stuff, but it doesn't change anything.

Second error : can't reproduce, but in case I have changed the logic to avoid any out of range.
