### ISSUE TITLE
Ghost exit button in the menu

### ISSUE THREAD

**Issue by Herschel-The-Cauchois** [Herschel-The-Cauchois/Efrarcade-TheHowls#24]
https://github.com/Herschel-The-Cauchois/Efrarcade-TheHowls/assets/133710162/211c6358-3da7-4486-88b2-a361795aaa5f

Clicking on the back button creates an unremovable exit button that cannot be accessed.

**Comment by Pverte** [comment]
Solved, there were twice the loading of the background. By removing one, it but the background everywhere and then properly reload the back, hiding the exit button
